### ISSUE TITLE
NextUI initialization and using Navbar having lots of error

### ISSUE THREAD

**Issue by YueMeiHong** [YueMeiHong/mokoblog#1]
I follow the NextUI Guide (or try follow ) and using all file (but change the .js to tsx, and import delete the .js part for every file). After hit npm start. I didn't get a clean page with my Navbar.

![图片](https://github.com/YueMeiHong/mokoblog/assets/86508535/8ffc943d-8bdb-4ec4-bbc0-3615306521bb)
![图片](https://github.com/YueMeiHong/mokoblog/assets/86508535/de5a4d72-2d20-456f-a81c-5c5106e4937b)

**Comment by kiochan** [comment]
I create a MR for it, pls check and merge if everything's alright.
